modules:

  icmp:
    prober: icmp
    timeout: 10s
    icmp:
      preferred_ip_protocol: "ip4"

  http_2xx:
    prober: http
    timeout: 10s
    http:
      preferred_ip_protocol: "ip4"

  dns_smsc:
    prober: dns
    timeout: 10s
    dns:
      query_name: "smsc.ru"
      query_type: "A"
      transport_protocol: "udp"
      preferred_ip_protocol: "ip4" 
      valid_rcodes:
        - NOERROR

  dns_dadata:
    prober: dns
    timeout: 10s
    dns:
      query_name: "dadata.ru"
      query_type: "A"
      transport_protocol: "udp"
      preferred_ip_protocol: "ip4" 
      valid_rcodes:
        - NOERROR
