version: '3.5'

services:
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Конфиг Prometheus
      - ./prometheus/data:/prometheus  # Volume для хранения данных
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=31d'
#    networks:
#      - monitoring_net
    user: root

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./grafana/lib:/var/lib/grafana  # Volume для хранения данных Grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
#      - ./grafana/provisioning/plugins/src/:/var/lib/grafana/plugins/
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS="alexanderzobnin-zabbix-app"
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.psbins.ru:587
      - GF_SMTP_FROM_ADDRESS=noreply@psbins.ru
      - GF_SMTP_USER=noreply@psbins.ru
      - GF_SMTP_SECURE_PASSWORD=your_password
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 8582:3000
#    networks:
#      - monitoring_net
    user: root

#networks:
#  monitoring_net:
#    driver: bridge