version: '3.5'

services:
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Конфиг Prometheus
      - ./prometheus/data:/prometheus  # Volume для хранения данных
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=31d'
    user: root
    extra_hosts:
      - "wwwdms-test-fe01:192.168.40.169"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.home.local`)"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    networks:
      - traefik-net


  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./grafana/lib:/var/lib/grafana                    # Volume для хранения данных Grafana
      - ./grafana/provisioning:/etc/grafana/provisioning  # Volume для provisioned конфигураций
      - ./grafana/plugins:/var/lib/grafana/plugins        # Volume для папок с плагинами
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.company.ru:587
      - GF_SMTP_FROM_ADDRESS=noreply@company.ru
      - GF_SMTP_USER=noreply@company.ru
      - GF_SMTP_SECURE_PASSWORD=your_password
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    user: root
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.home.local`)"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
