version: '3.5'

services:
  prometheus:
    image: prom/prometheus:v2.53.4
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Конфиг Prometheus
      - ./prometheus/data:/prometheus  # Volume для хранения данных
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=31d'
    user: root

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./grafana/lib:/var/lib/grafana                    # Volume для хранения данных Grafana
      - ./grafana/provisioning:/etc/grafana/provisioning  # Volume для provisioned конфигураций
      - ./grafana/plugins:/var/lib/grafana/plugins        # Volume для папок с плагинами
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.company.ru:587
      - GF_SMTP_FROM_ADDRESS=noreply@company.ru
      - GF_SMTP_USER=noreply@company.ru
      - GF_SMTP_SECURE_PASSWORD=your_password
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 8582:3000
    user: root


  blackbox-exporter:
    image: prom/blackbox-exporter:v0.26.0
    container_name: blackbox-exporter
    restart: unless-stopped
    depends_on:
      - prometheus
    ports:
      - 9115:9115
    volumes:
      - ./blackbox_exporter/config.yaml:/etc/blackbox_exporter/config.yaml
    command:
      - '--config.file=/etc/blackbox_exporter/config.yaml'


#  dns_exporter:
#    image: tykling/dns_exporter:latest
#    ports:
#      - 15353:15353
#    volumes:
#      - ./dns_exporter.yml:/home/nonroot/dns_exporter.yml
