apiVersion: 1

groups:
  - orgId: 1
    folder: NodeExporter
    name: group_1m
    interval: 1m

    rules:
      - uid: alert_hdd_usage_warn_uid
        title: HDD Usage Warning (>80%)
        condition: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: "High HDD usage detected (warning)"
          description: "HDD usage is above 80% for 5 minutes"
          __dashboardUid__: dashboard_node_exporter_uid
          __panelId__: "152"
        labels:
          severity: "warning"
          team: "admins"
        isPaused: false
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: datasource_prometheus_uid 
            model:
              expr: >
                round (
                  max by (nodename, mountpoint) (
                    (
                      (
                        node_filesystem_size_bytes{device!~'rootfs'} - node_filesystem_avail_bytes{device!~'rootfs'}
                      ) / node_filesystem_size_bytes {device!~'rootfs'}
                    ) * on(instance) group_left(nodename) node_uname_info
                  ) * 100, 0.1
                ) > 80
              instant: true
              intervalMs: 10000
              maxDataPoints: 43200 
              refId: A

      - uid: alert_hdd_usage_crit_uid
        title: HDD Usage Critical (>95%)
        condition: A
        noDataState: OK
        execErrState: Error
        for: 5m
        annotations:
          summary: "High HDD usage detected (critical)"
          description: "HDD usage is above 95% for 5 minutes"
          __dashboardUid__: dashboard_node_exporter_uid
          __panelId__: "152"
        labels:
          severity: "critical"
          team: "admins"
        isPaused: false
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: datasource_prometheus_uid 
            model:
              expr: >
                round (
                  max by (nodename, mountpoint) (
                    (
                      (
                        node_filesystem_size_bytes{device!~'rootfs'} - node_filesystem_avail_bytes{device!~'rootfs'}
                      ) / node_filesystem_size_bytes {device!~'rootfs'}
                    ) * on(instance) group_left(nodename) node_uname_info
                  ) * 100, 0.1
                ) > 95           
              instant: true
              intervalMs: 10000
              maxDataPoints: 43200 
              refId: A

      - uid: alert_cpu_usage_warn_uid
        title: CPU Usage Warning (>70%)
        condition: "A"
        noDataState: OK
        execErrState: Error
        for: "5m"
        annotations:
          summary: "High CPU usage detected (warning)"
          description: "CPU usage is above 70% for 5 minutes"
          __dashboardUid__: dashboard_node_exporter_uid
          __panelId__: "77"
        labels:
          severity: "warning"
          team: "admins"
        isPaused: false
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: datasource_prometheus_uid 
            model:
              expr: >
                round (
                  avg by (nodename) (
                    (
                      1 - irate(node_cpu_seconds_total{mode='idle'}[5m])
                    ) * on(instance) group_left(nodename) node_uname_info
                  ) * 100, 0.1
                ) > 70
              instant: true
              intervalMs: 10000
              maxDataPoints: 43200
              refId: "A"

      - uid: alert_cpu_usage_crit_uid
        title: CPU Usage Critical (>85%)
        condition: "A"
        noDataState: OK
        execErrState: Error
        for: "5m"
        annotations:
          summary: "High CPU usage detected (critical)"
          description: "CPU usage is above 85% for 5 minutes"
          __dashboardUid__: dashboard_node_exporter_uid
          __panelId__: "77"
        labels:
          severity: "critical"
          team: "admins"
        isPaused: false
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: datasource_prometheus_uid 
            model:
              expr: >
                round (
                  avg by (nodename) (
                    (
                      1 - irate(node_cpu_seconds_total{mode='idle'}[5m])
                    ) * on(instance) group_left(nodename) node_uname_info
                  ) * 100, 0.1
                ) > 85
              instant: true
              intervalMs: 10000
              maxDataPoints: 43200
              refId: "A"

      - uid: alert_ram_usage_warn_uid
        title: RAM Usage Warning (>80%)
        condition: "A"
        noDataState: OK
        execErrState: Error
        for: "5m"
        annotations:
          summary: "High RAM usage detected (warning)"
          description: "RAM usage is above 80% for 5 minutes"
          __dashboardUid__: dashboard_node_exporter_uid
          __panelId__: "78"
        labels:
          severity: "warning"
          team: "admins"
        isPaused: false
        data:
          - refId: "A"
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: datasource_prometheus_uid
            model:
              expr: >
                round (
                  max by (nodename) (
                    (
                      (
                        node_memory_MemTotal_bytes 
                        - node_memory_MemFree_bytes 
                        - node_memory_Buffers_bytes 
                        - node_memory_Cached_bytes
                      ) / node_memory_MemTotal_bytes
                    ) * on(instance) group_left(nodename) node_uname_info
                  ) * 100, 0.1
                ) > 80
              instant: true
              intervalMs: 10000
              maxDataPoints: 43200
              refId: "A"

      - uid: alert_ram_usage_crit_uid
        title: RAM Usage Critical (>95%)
        condition: "A"
        noDataState: OK
        execErrState: Error
        for: "5m"
        annotations:
          summary: "High RAM usage detected (critical)"
          description: "RAM usage is above 95% for 5 minutes"
          __dashboardUid__: dashboard_node_exporter_uid
          __panelId__: "78"
        labels:
          severity: "critical"
          team: "admins"
        isPaused: false
        data:
          - refId: "A"
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: datasource_prometheus_uid
            model:
              expr: >
                round (
                  max by (nodename) (
                    (
                      (
                        node_memory_MemTotal_bytes 
                        - node_memory_MemFree_bytes 
                        - node_memory_Buffers_bytes 
                        - node_memory_Cached_bytes
                      ) / node_memory_MemTotal_bytes
                    ) * on(instance) group_left(nodename) node_uname_info
                  ) * 100, 0.1
                ) > 95
              instant: true
              intervalMs: 10000
              maxDataPoints: 43200
              refId: "A"