apiVersion: 1

contactPoints:
    - orgId: 1
      name: Default PSBS alerting email
      receivers:
        - uid: contactpoint_default_psbs_uid
          type: email
          settings:
            addresses: |-
              lysikovaev@psbins.ru
              atkachenko@psbii.ru
            singleEmail: false
#            message: '{{ template "custom_email.message" .}}'
#            subject: '{{ template "custom_email.subject" .}}'
          disableResolveMessage: false

muteTimes:
    - orgId: 1
      name: Default mute times (no_weekends)
      time_intervals:
        - weekdays: [saturday, sunday]

policies:
    - orgId: 1
      receiver: Default PSBS alerting email
      group_by:
        - grafana_folder
        - alertname
      routes:
        - receiver: Default PSBS alerting email
          mute_time_intervals: 
            - Default mute times (no_weekends)

#templates:
#    - orgId: 1
#      name: custom_email.message
#      template: |
#        {{ define "custom_email.message" }}
#          Lorem ipsum - Custom alert!
#        {{ end }}
#    - orgId: 1
#      name: custom_email.subject
#      template: |
#        {{ define "custom_email.subject" }}
#        {{ len .Alerts.Firing }} firing alert(s), {{ len .Alerts.Resolved }} resolved alert(s)
#        {{ end }}